In [1]:
import numpy as np

# 1.Create a null vector of size 10 but the fifth value which is 1.


In [3]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2.Create a vector with values ranging from 10 to 49.

In [4]:
vect=np.arange(10,50)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3.Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
arr1=np.nonzero([1,2,0,0,4,0])
arr1

(array([0, 1, 4], dtype=int64),)

# 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [10]:
arr2=np.random.rand(10,10)
arr2

array([[0.41056875, 0.30537746, 0.96067162, 0.92351696, 0.87842799,
        0.1829454 , 0.30647516, 0.1813186 , 0.99558713, 0.42329072],
       [0.51178523, 0.56489127, 0.08083155, 0.8813371 , 0.64413007,
        0.80482386, 0.54471587, 0.72120501, 0.06411664, 0.9269768 ],
       [0.67329053, 0.51986609, 0.12067697, 0.16913379, 0.89833651,
        0.12968137, 0.82096206, 0.37130323, 0.54248751, 0.33494595],
       [0.02860403, 0.17516793, 0.54508591, 0.68211509, 0.20766327,
        0.95548239, 0.20773335, 0.84997174, 0.36749984, 0.9670311 ],
       [0.22244812, 0.90253948, 0.38047545, 0.19205639, 0.46184821,
        0.91011534, 0.84175444, 0.6860498 , 0.96477558, 0.24653864],
       [0.29269085, 0.19417668, 0.46901841, 0.39581693, 0.38743266,
        0.7198882 , 0.18625893, 0.25304492, 0.41763257, 0.93323633],
       [0.92673953, 0.45887541, 0.70967782, 0.68024104, 0.01209907,
        0.87465836, 0.68766901, 0.64470195, 0.89424075, 0.80704127],
       [0.63516581, 0.57492763, 0.6068201

In [11]:
arr2_min=arr2.min()
arr2_max=arr2.max()
print(arr2_min,arr2_max)

0.012099072438387481 0.9955871296301451


# 6. Create a random vector of size 30 and find the mean value.


In [12]:
vect2=np.random.random(30)
mean=vect2.mean()
mean

0.4901405991347628